export const ROUTES_BACKEND = {
    LOGIN: '/auth/v1/token?grant_type=password',
    SIGNUP: '/auth/v1/signup',
    HOME: '/',
    PROFILE: '/profile',
    SETTINGS: '/settings',
    LOGOUT: '/logout',
    GET_PROJECTS: '/api/v1/projects',
    POST_PROJECTS: '/api/v1/projects',
    DELETE_PROJECTS: '/api/v1/projects',
    GET_BATCHS_ID: '/api/v1/batches?projectId=',
    GET_BATCH_STATISTICS: '/api/v1/batches/statistics',
    ADD_BATCH: '/api/v1/batches',
    DELETE_BATCH:'/api/v1/batches',
    GET_TASKS: '/api/v1/tasks',
    POST_TASKS: '/api/v1/tasks',
    PUT_TASKS: '/api/v1/tasks',
    DELETE_TASKS: '/api/v1/tasks',
}

export const ROUTES_FRONTEND = {
    LOGIN: '/login',
    SIGNUP: '/signup',
    HOME: '/',
    PROFILE: '/profile',
    SETTINGS: '/settings',
    LOGOUT: '/logout',
    DASHBOARD: '/dashboard',
    PROJECTS: '/projects',
    PROJECT_TABS: '/projects/:projectId',
    ALL_TASKS: '/projects/:projectId/alltasks',
    BATCH: '/projects/:projectId/batches',
    TASKS: '/projects/:projectId/batches/:batchId/tasks',
    ANNOTATIONS: '/projects/:projectId/batches/:batchId/tasks/:taskId',
    PROJECT_DELIVERY: '/projects/:projectId/delivery',
    PROJECT_TEAM: '/projects/:projectId/team',
    TEAM:'/team',
    ACTIVITY_LOGS: '/activity-logs',
    DELIVERY: '/delivery',
    DELIVERY_TASKS: '/delivery/:deliveryBatchId/tasks',
    TIME_TRACKING: '/time-tracking',
    ATTENDANCE: '/attendance',
    SESSION_HISTORY: '/session-history',
}